//
//  DiscoverWorker.swift
//  synema
//
//  Created by syndromme on 24/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RxSwift
import Moya

class DiscoverWorker
{
  func requestMovies(request: Discover.APIModel.Request) -> Single<Discover.APIModel.Response> {
    return Provider.rx.request(.discover(request: request))
      .map { moyaResponse -> Discover.APIModel.Response in
        guard let response = try? moyaResponse.mapObject(Discover.APIModel.Response.self, context: nil) else {
          throw AppError.genericError(message: "#Failed mapping")
        }
        
        if moyaResponse.statusCode == 200 {
          return response
        } else {
          throw AppError.genericError(message: moyaResponse.description)
        }
    }
  }
}
