//
//  DiscoverPresenter.swift
//  synema
//
//  Created by syndromme on 24/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DiscoverPresentationLogic
{
  func presentMovies(response: [Movie])
}

class DiscoverPresenter: DiscoverPresentationLogic
{
  weak var viewController: DiscoverDisplayLogic?
  
  // MARK: Do something
  func presentMovies(response: [Movie]) {
    viewController?.displayMovies(result: response)
  }
}
