//
//  MovieDetailWorker.swift
//  synema
//
//  Created by syndromme on 24/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RxSwift
import Moya

class MovieDetailWorker
{
  func requestMovies(path: String) -> Single<Movie> {
    return Provider.rx.request(.movieDetail(path: path))
      .map { moyaResponse -> Movie in
        guard let response = try? moyaResponse.mapObject(Movie.self, context: nil) else {
          throw AppError.genericError(message: "#Failed mapping")
        }
        
        if moyaResponse.statusCode == 200 {
          return response
        } else {
          throw AppError.genericError(message: moyaResponse.description)
        }
    }
  }
  
  func requestReview(path: String, request: MovieDetail.APIModel.Request) -> Single<MovieDetail.APIModel.ResponseReview> {
    return Provider.rx.request(.movieReview(path: path, request: request))
      .map { moyaResponse -> MovieDetail.APIModel.ResponseReview in
        guard let response = try? moyaResponse.mapObject(MovieDetail.APIModel.ResponseReview.self, context: nil) else {
          throw AppError.genericError(message: "#Failed mapping")
        }
        
        if moyaResponse.statusCode == 200 {
          return response
        } else {
          throw AppError.genericError(message: moyaResponse.description)
        }
    }
  }
  
  func requestTrailer(path: String) -> Single<MovieDetail.APIModel.ResponseTrailer> {
    return Provider.rx.request(.movieTrailer(path: path))
      .map { moyaResponse -> MovieDetail.APIModel.ResponseTrailer in
        guard let response = try? moyaResponse.mapObject(MovieDetail.APIModel.ResponseTrailer.self, context: nil) else {
          throw AppError.genericError(message: "#Failed mapping")
        }
        
        if moyaResponse.statusCode == 200 {
          return response
        } else {
          throw AppError.genericError(message: moyaResponse.description)
        }
    }
  }
}
