//
//  GenreListModels.swift
//  synema
//
//  Created by syndromme on 23/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import ObjectMapper

enum GenreList
{
  // MARK: Use cases
  
  enum APIModel
  {
    class Request: Mappable
    {
      required init?(map: Map) {
        
      }
      
      func mapping(map: Map) {
        
      }
      
    }
    
    class Response: Mappable
    {
      var genres: [Genre] = []
      
      required init?(map: Map) {
        
      }
      
      func mapping(map: Map) {
        genres   <- map["genres"]
      }
    }
    
    class ViewModel: Mappable
    {
      required init?(map: Map) {
        
      }
      
      func mapping(map: Map) {
        
      }
      
    }
  }
}

class Genre: Mappable {
  var genreID: Int = 0
  var genreName: String = ""
  
  init() {
    
  }
  
  required init?(map: Map) {
    
  }
  
  func mapping(map: Map) {
    genreID             <- map["id"]
    genreName           <- map["name"]
  }
}
