//
//  GenreListWorker.swift
//  synema
//
//  Created by syndromme on 23/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RxSwift
import Moya

class GenreListWorker
{
//  func getGenres(completionHandler: @escaping (ApiResponse.GetGenreResponse) -> Void) {
//    Provider.request(.genre) { (result) in
//      switch result {
//      case let .success(response):
//        if let responseValue = try? response.mapObject(GenreList.APIModel.Response.self) {
//          print("#success \(responseValue.toJSONString(prettyPrint: true)!)")
//          completionHandler(.success(response: responseValue))
//        } else {
//          print("#Failed mapping")
//          completionHandler(.error(message: "#Failed mapping"))
//        }
//      case let .failure(error):
//        completionHandler(.error(message: error.localizedDescription))
//      }
//    }
//  }
  
  func requestGenres() -> Single<GenreList.APIModel.Response> {
    return Provider.rx.request(.genre)
      .map { moyaResponse -> GenreList.APIModel.Response in
        guard let response = try? moyaResponse.mapObject(GenreList.APIModel.Response.self, context: nil) else {
          throw AppError.genericError(message: "#Failed mapping")
        }
        
        if moyaResponse.statusCode == 200 {
          return response
        } else {
          throw AppError.genericError(message: moyaResponse.description)
        }
    }
  }
}
