//
//  GenreListRouter.swift
//  synema
//
//  Created by syndromme on 23/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GenreListRoutingLogic
{
  func routeToDiscovery()
}

protocol GenreListDataPassing
{
  var dataStore: GenreListDataStore? { get }
}

class GenreListRouter: NSObject, GenreListRoutingLogic, GenreListDataPassing
{
  weak var viewController: GenreListViewController?
  var dataStore: GenreListDataStore?
  
  // MARK: Routing
  
  func routeToDiscovery() {
    let nav = viewController?.presentingViewController as! UINavigationController
    let destinationVC = nav.topViewController as! DiscoverViewController//DiscoverViewController(nibName: "BaseTableView", bundle: nil)
    var destinationDS = destinationVC.router!.dataStore!
    passDataToDiscovery(source: dataStore!, destination: &destinationDS)
    navigateToDiscovery(source: viewController!, destination: destinationVC)
  }
  // MARK: Navigation
  
  func navigateToDiscovery(source: GenreListViewController, destination: DiscoverViewController)
  {
    source.dismiss(animated: true, completion: nil)
  }
  
  // MARK: Passing data
  
  func passDataToDiscovery(source: GenreListDataStore, destination: inout DiscoverDataStore)
  {
    destination.genres = source.genres
  }
}
