//
//  GenreListPresenter.swift
//  synema
//
//  Created by syndromme on 23/06/19.
//  Copyright (c) 2019 syndromme. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenreListPresentationLogic
{
  func presentGenres(response: [Genre])
  func presentFilter()
}

class GenreListPresenter: GenreListPresentationLogic
{
  weak var viewController: GenreListDisplayLogic?
  
  // MARK:
  func presentGenres(response: [Genre]) {
    viewController?.displayGenres(result: response)
  }
  
  func presentFilter() {
    viewController?.displayFilter()
  }
}
